sudo: required
dist: trusty

language: scala
scala: 2.13.3

jdk:
  - openjdk11

git:
  depth: 3

before_install:
 - sudo apt-get update -q
 - sudo apt-get install texlive-full texlive-latex-extra texlive-lang-all texlive-lang-swedish -y

script:
 - sbt pdfCompendium
