name: Build
on: [push]
jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup dependencies
        run: sudo apt-get install texlive-full texlive-latex-extra texlive-lang-all -y
        shell: bash
      - name: SBT Build
        run: sbt "about;workspace/compile;build"
        shell: bash
